kind: pipeline
type: docker
name: default

platform:
  os: windows
  
clone:
  git:
    image: plugins/git
    tags: false

steps:
- name: test
  # image: mcr.microsoft.com/dotnet/core/aspnet:latest
  image: golang
  commands:
  - echo windows-docker-4
