kind: pipeline
type: docker
name: default

platform:
  os: windows
  
workspace:
  base: /go
  path: src/github.com/drone-demos/drone-with-go  
  
#clone:
#  skip_verify: true
  
steps:
- name: test
  # image: mcr.microsoft.com/dotnet/core/aspnet:latest
  image: golang
  commands:
  - echo windows-docker-6
