kind: pipeline
type: docker
name: default

platform:
  os: windows

steps:
- name: test
  # image: mcr.microsoft.com/dotnet/core/aspnet:latest
  image: plugins/manifest
  commands:
  - echo windows-docker-4
  # - dir
